#!/system/bin/sh

mkdir -p /data/ssh/empty
cd /data/ssh

ECDSA_KEY=ssh_host_ecdsa_key
ECDSA_PUB_KEY=ssh_host_ecdsa_key.pub
ED25519_KEY=ssh_host_ed25519_key
ED25519_PUB_KEY=ssh_host_ed25519_key.pub
RSA_KEY=ssh_host_rsa_key
RSA_PUB_KEY=ssh_host_rsa_key.pub
SSHD_CONFIG=sshd_config
INSTALLED_SSHD_CONFIG=/system/etc/sshd_config

if [ ! -f $ECDSA_KEY ]; then
    /system/bin/ssh-keygen -t ecdsa -f $ECDSA_KEY -N ""
    chmod 600 $ECDSA_KEY
fi

if [ ! -f $ED25519_KEY ]; then
    /system/bin/ssh-keygen -t ed25519 -f $ED25519_KEY -N ""
    chmod 600 $ED25519_KEY
fi

if [ ! -f $RSA_KEY ]; then
    /system/bin/ssh-keygen -t rsa -f $RSA_KEY -N ""
    chmod 600 $RSA_KEY
fi

if [ ! -f $SSHD_CONFIG ]; then
    cat $INSTALLED_SSHD_CONFIG > $SSHD_CONFIG
fi

chmod 700 /data/ssh/empty

# run sshd and capture output to logcat
/system/bin/logwrapper /system/bin/sshd -f $SSHD_CONFIG -D
